language: cpp

matrix:
  include:
  - os: windows
    env: configuration=Debug
  - os: windows
    env: configuration=Release
    
before_script:
  - if [ $TRAVIS_OS_NAME == 'windows' ]; then
    mkdir build;
    cd build;
    cmake .. -G "Visual Studio 15 2017" -A Win32;
    fi

script:
  - if [ $TRAVIS_OS_NAME == 'windows' ]; then
    cmake --build . --config $configuration;
    fi
